POST http://localhost:8080/graphql
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "query": "mutation { updateRestaurant(id: 3, input: {name: \"PizzaPancake\"}) { id name address owner { username } } }"
}