POST http://localhost:8080/graphql
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "query": "mutation { createDish(input: {name: \"Pancake\", price: 8, restaurantId: 3}) { id name price } }"
}