POST http://localhost:8080/graphql
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "query": "mutation { updateDish(id: 5, input: {name: \"Cool Pancake\", price: 25}) { id name price } }"
}
