POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTczODI2NzE4MywiaWF0IjoxNzM4MjYzNTgzfQ.MLTpetnkiujXhAwfotpYolF6fz1plOTKHsVbVHXp6yo

{
  "query": "mutation { createUser(input: { username: \"newuser4\", password: \"password123\", fullName: \"New User\", role: \"USER\" }) { id username fullName role } }"
}