POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrMTIzNDU2Nzg5Iiwicm9sZXMiOlsiUkVTVEFVUkFOVCIsIlVTRVIiXSwiZXhwIjoxNzQwMTE0MTU3LCJpYXQiOjE3NDAxMTA1NTd9.gzbx-snt42mL5cwMQbg4QYiAcZ6aIwlWjSz3lmtM3Bo

{
  "query": "query { user(id: 9) { id phoneNumber fullName } }"
}
