POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "phoneNumber": "+123456789",
  "password": "password",
  "fullName": "Test Testerovich",
  "roles": ["USER", "RESTAURANT"]
}


